Bus ticket
KorolElizavetaR/AndersenKorolER pull request #5
Opened 2024-11-07 07:10 UTC by KorolElizavetaR

2024-11-07 08:02 UTC, Darya-Drutsko requested changes
Needs clarification for some topics
Good that you're using additional info, but key point from my side that you need to know why do you write this or that way, what annotations mean for example

2024-11-07 08:02 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/model/user/Admin.java
> +	{
formatting

2024-11-12 16:49 UTC, KorolElizavetaR commented on BusTickets/pom.xml
> +		<dependency>
Removed unnecessary dependencies.

2024-11-12 16:51 UTC, KorolElizavetaR commented on BusTickets/src/main/java/andersen/dev/tickets/constraint/EvenConstraint.java
> +	public boolean isValid(Integer value, ConstraintValidatorContext context) {
This method Overrides method isValid that must be implemented. But inside method i don't use this variable/

2024-11-13 06:14 UTC, KorolElizavetaR commented on BusTickets/src/main/java/andersen/dev/tickets/constraint/Even.java
> +	Class<?>[] groups() default {};
As a source of this code says, it's a "boilerplate code to conform to the Spring standards". I guess these two signatures of methods can handle some more complicated logic with params, but for now they are mostly here just to make a code work.

2024-11-18 07:01 UTC, Darya-Drutsko commented on BusTickets/src/main/java/andersen/dev/tickets/constraint/Even.java
> +	Class<?>[] groups() default {};
That's the case. When you're developing smth, you need to know why have you added this or that line. 
It's not the problem that you've found some solution, but when reusing it you need understand what happens

So if we remove 17 line the code will not work?

2024-11-18 07:01 UTC, Darya-Drutsko commented on BusTickets/src/main/java/andersen/dev/tickets/constraint/Even.java
> +	Class<? extends Payload>[] payload() default {};
Do we use it somehow?

2024-11-18 07:22 UTC, Darya-Drutsko commented on BusTickets/src/main/java/andersen/dev/tickets/service/TicketDAO.java
> +	private TicketValidator validator;
Validation is not the responsibility of DAO class
For DAO we're implementing all the functionality required for action with our model objects
https://www.baeldung.com/java-dao-pattern

2024-11-18 07:22 UTC, Darya-Drutsko commented on BusTickets/src/main/java/andersen/dev/tickets/validator/TicketValidator.java
> +	List<Ticket> allTickets;
Why all tickets stored in validator class?
Seems like different responsibility, so create please TicketRepository for saving all tickets

2024-11-18 07:22 UTC, Darya-Drutsko commented on BusTickets/src/main/java/andersen/dev/tickets/validator/TicketValidator.java
> +	private int ticketCounterBeforeCheckingViolations;
Do we actually need this field? Does it somewhere will be different from allTicket.size() ?

2024-11-18 07:22 UTC, Darya-Drutsko commented on BusTickets/src/main/resources/application.properties~
> +json.ticket.filepath = path to ticket json
set please here path that is valid for your app

2024-11-18 07:22 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/model/ContentPrintering.java
> +		Field[] fields = this.getClass().getDeclaredFields();
separate it into 2 methods - for getting field names and for getting method names. Also place these methods in util class

2024-11-18 07:22 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/model/ContentPrintering.java
> +public interface ContentPrintering {
Could also be renamed as Printable

2024-11-18 07:22 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/model/ContentPrintering.java
> +	default void printer() {
Could also be renamed as 'print'

2024-11-18 07:22 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/model/user/Client.java
> +		super(service, "Client");
Client and Admin could be as enum

2024-11-18 07:22 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/model/user/User.java
> +	protected final TicketService service;
Inside our model classes we're not adding services as a field, models representing only the structure of the objects
And services use model for performing some action, not vice versa

2024-11-18 07:22 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/service/TicketService.java
>  	List<Ticket> tickets = new ArrayList<>();
The same comment for storing tickets inside service, create please separate class for storing

2024-11-18 08:09 UTC, KorolElizavetaR commented on BusTickets/src/main/java/andersen/dev/tickets/constraint/Even.java
> +	Class<?>[] groups() default {};
Yes, i've checked. Without this code, ConstraintDefinitionException is thrown.

2024-11-18 08:10 UTC, KorolElizavetaR commented on BusTickets/src/main/java/andersen/dev/tickets/constraint/Even.java
> +	Class<? extends Payload>[] payload() default {};
Same as above.

2024-11-20 13:55 UTC, KorolElizavetaR commented on BusTickets/src/main/java/andersen/dev/tickets/service/TicketService.java
> +@Component
Doesn't really matters whether we are using @Service or @Component here. I guess just seeing  @Service without using Spring Data feels odd.

2024-11-20 14:01 UTC, KorolElizavetaR commented on BusTickets/src/main/java/andersen/dev/tickets/validator/TicketValidator.java
> +	private int ticketCounterBeforeCheckingViolations;
Before TicketRepository field, the difference was just in convenience, but now it serves a purpose of storing a full counter of tickets since we must not access repository from a higher levels (probably storing a counter of violations would make more sense?)

2024-11-24 20:57 UTC, Darya-Drutsko commented on BusTickets/src/main/java/andersen/dev/tickets/repository/TicketRepository.java
> +@Scope (ConfigurableBeanFactory.SCOPE_PROTOTYPE)
Didn't catch the idea of having 2 repositories at the same time...

Usually repositories for connection for our storage, so if you're creating 2 instances this assumed from me that you'll have 2 different sources of tickets

2024-11-24 20:57 UTC, Darya-Drutsko commented on BusTickets/src/main/java/andersen/dev/tickets/service/TicketService.java
> +@Component
Didn't catch the connection with Spring Data :)

2024-11-24 20:57 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/model/Ticket.java
> +//	public String shared(String phone) {
Commented code?

2024-11-24 20:57 UTC, Darya-Drutsko commented on BusTickets/src/main/java/andersen/dev/tickets/validator/TicketValidator.java
> +	private int ticketCounterBeforeCheckingViolations;
Actually if you have a field in validator like 'ticketsCount', 'invalidTicketsCount' makes your app very connected to values that is executes, the functionality is not flexible and reusable(what if currently we need to check all tickets, but after only first 10 and so on...) 
The as for me Validator don't need to have any state, the main goal - execute validation and return some result :)
If you want to have some statistics for further displaying - wdyt about having separate Statistics object for it?) so in our service we could do anything with the results

2024-12-01 20:12 UTC, Darya-Drutsko approved these changes

2024-12-01 20:12 UTC, Darya-Drutsko commented on Task2Tickets/src/main/java/andersen/task/tickets/service/TicketService.java
> +		Printable.super.printMethods();;
Why do we need here Printable.super? not just printMethods()?
and double ; here :)

2024-12-02 06:23 UTC, merged